update KSUN submodule

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -77,8 +77,30 @@ jobs:
       - name: ⭐Checkout repository with submodules
         uses: actions/checkout@v4
         with:
-          submodules: 'recursive'
+          submodules: true
 
+          - name: "💡 Setup KernelSu"
+        run: |
+          if [ -d "./KernelSU-Next" ]; then rm -rf "./KernelSU-Next"; fi
+          if [ -d "./drivers/KernelSU-Next" ]; then rm -rf "./drivers/KernelSU-Next"; fi 
+          curl -LSs "https://raw.githubusercontent.com/Star-Seven/KernelSU-Next/next/kernel/setup.sh" | bash -
+
+      - name: "😄 Setup and Apply susfs4ksu Patches"
+        run: |
+           set -e
+
+           # Backport SUSFS to Linux 4.14
+           git clone https://github.com/Star-Seven/susfs4ksu -b M62-backport-Susfs susfs4ksu-repo
+
+           cp susfs4ksu-repo/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
+           cp susfs4ksu-repo/kernel_patches/fs/* fs/
+           cp susfs4ksu-repo/kernel_patches/include/linux/* include/linux/
+           cd ./KernelSU-Next
+           patch -p1 -F 3 < 10_enable_susfs_for_ksu.patch || { echo "Failed to apply patch"; exit 1; }
+           cd ..
+           patch -p1 --verbose < susfs4ksu-repo/kernel_patches/50_add_susfs_in_kernel-4.14.patch
+           echo "Successfully applied susfs4ksu patches"
+           
       - name: ⚙️ setting permission
         run: chmod +x build.sh
 
